repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.8
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.400
  hooks:
  - id: pyright
